### PR TITLE
Updated Styling

### PR DESCRIPTION
**Pull request by spiderxm**
Added Styling to Form and updated styling of Poster 
Deployed the site using netlify Link added in README.md
Screenshot 2020-12-22 at 7 14 59 PM

### CODE REVIEW

**Comment by SaxenaKartik** [comment]
Great work @spiderxm 
I love the new form and poster styling :+1: 

image

Update needed :  I would wish to keep the **link** and **contact** style similar to the older version as shown below 

image

Moreover, it would be great if all the **three generate buttons** of the form are in the same line

**Comment by spiderxm** [comment]
Added Dark mode for poster
Fixed Form Styling
Restored contact details format 
Added divider

**Comment by spiderxm** [comment]
Light mode

**Comment by spiderxm** [comment]
Dark Mode

**Comment by spiderxm** [comment]
Screenshot 2020-12-27 at 11 14 48 AM
Updated UI

**Comment by SaxenaKartik** [comment]
Loved it! :heart: Great work @spiderxm :+1:

**Pull request merged**
